config/routes.rb
Rails.application.routes.draw do

  resources :contacts do
    resources :notes
    resources :tasks
    get :update_variable
  end

  resources :companies

  devise_for :users
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "search/index"

  get '/all-tasks/' => 'tasks#allTasks', :as => :all_tasks
  get '/all-notes/' => 'notes#allNotes', :as => :all_notes
  get 'users/:id/preferences' => 'users#preferences', :as => :preferences

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :contact

  def note_made_at
    created_at.try(:strftime, "%B %e, %Y")
  end

  def author_and_time
    "#{self.author}, #{note_made_at}"
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(contact_id: params[:contact_id])
    @contact_id = params[:contact_id]
  end

  def allNotes
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new(contact_id: params[:contact_id])
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to root_path, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:body, :author, :contact_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note, url: contact_notes_path do |f|
  - if note.errors.any?
    #error_explanation
      %h2
        = pluralize(note.errors.count, "error")
        prohibited this note from being saved:
      %ul
        - note.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :author
    = f.text_field :author
    = f.hidden_field :contact_id, :value => params[:contact_id]
  .actions
    = f.submit

app/views/notes/allNotes.html.haml
%p#notice= notice
%h1 Notes
%table
  %thead
    %tr
      %th Body
      %th Author
      %th{:colspan => "3"}
  %tbody
    - @notes.each do |note|
      %tr
        %td= note.body
        %td= note.author
        %td= link_to 'Show', contact_note_path(note.contact_id, note.id)

%br/

= link_to 'Back', all_notes_path

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/new.html.haml
%h1 New Note
= render 'form', note: @note
= link_to 'Back', contact_notes_path

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @note.author %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>