config/routes.rb
Rails.application.routes.draw do

  resources :contacts do
    resources :notes
    resources :tasks
    get :update_variable
  end

  resources :companies

  devise_for :users
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "search/index"

  get '/all-tasks/' => 'tasks#allTasks', :as => :all_tasks
  get '/all-notes/' => 'notes#allNotes', :as => :all_notes
  get 'users/:id/preferences' => 'users#preferences', :as => :preferences

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :contact

  def deadline
    start_date.try(:strftime, "%B %e, %Y")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  def allTasks
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to contact_path(4), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :detail, :author, :contact_id, :completed, :start_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task, url: contact_tasks_path do |f|
  - if task.errors.any?
    #error_explanation
      %h2
        = pluralize(task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - task.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :detail
    = f.text_area :detail
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.hidden_field :contact_id, :value => params[:contact_id]
  .field
    = f.label :completed
    = f.check_box :completed
  .field
    = f.label :start_date
    = f.date_field :start_date
  .actions
    = f.submit

app/views/tasks/allTasks.html.haml
%p#notice= notice
%h1 Tasks
%table
  %thead
    %tr
      %th Title
      %th Detail
      %th Author
      %th Contact
      %th Deadline
      %th Completed
      %th{:colspan => "3"}
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.title
        %td= task.detail
        %td= task.author
        %td= task.contact_id
        %td= task.deadline
        %td= task.completed
        %td= link_to 'Show', contact_task_path(task.contact_id, task.id)
        %td= link_to 'Edit', edit_contact_task_path(task.contact_id, task.id)
        -#%td= link_to 'Destroy', contact_task, method: :delete, data: { confirm: 'Are you sure?' }

app/views/tasks/edit.html.haml
%h1 Editing Task
= render 'form', task: @task
= link_to 'Show', @contact_task
|
\#{link_to 'Back', contact_tasks_path}

app/views/tasks/new.html.haml
%h1 New Task
= render 'form', task: @task
= link_to 'Back', contact_tasks_path

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @task.detail %>
</p>

<p>
  <strong>Author:</strong>
  <%= @task.author %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @task.contact_id %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_contact_task_path(@task.contact_id, @task.id) %> |
<%= link_to 'Back', all_tasks_path %>