config/routes.rb
Rails.application.routes.draw do

  resources :contacts do
    resources :notes
    resources :tasks
    get :update_variable
  end

  resources :companies

  devise_for :users
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "search/index"

  get '/all-tasks/' => 'tasks#allTasks', :as => :all_tasks
  get '/all-notes/' => 'notes#allNotes', :as => :all_notes
  get 'users/:id/preferences' => 'users#preferences', :as => :preferences

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company
  has_many :notes
  has_many :tasks
  accepts_nested_attributes_for :tasks
  mount_uploader :image, ImageUploader
  include PgSearch
  pg_search_scope :search_by_full_name, :against => [:firstname, :surname]
  extend FriendlyId

  validates_presence_of :firstname
  validates_presence_of :surname
  validates_presence_of :company_id
  scope :alphabetical, -> (surname) { order('surname asc') }
  scope :nonalphabetical, -> (surname) { order('surname desc') }

  def name
    "#{self.firstname} #{self.surname}"
  end

  def initials
    name_to_split = self.name
    name_to_split.split.map(&:first).join
  end

  def age(birthday)
    (Time.now.to_s(:number).to_i - birthday.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def full_age
    "#{self.birthday.strftime('%e %B, %Y')} (#{self.age(self.birthday)} years old)"
  end

  def address
    @address_array = [self.address_street, self.address_street2, self.address_city, self.address_state, self.address_country, self.address_postcode]
    @address_array.reject(&:blank?).join(", ")
  end

  def address_line1
    @address_array = [self.address_street, self.address_street2]
    @address_array.reject(&:blank?).join(", ")
  end

  def address_line2
    @address_array = [self.address_city, self.address_state]
    @address_array.reject(&:blank?).join(", ")
  end

  def address_line3
    @address_array = [self.address_postcode, self.address_country]
    @address_array.reject(&:blank?).join(", ")
  end

  def work_address
    @work_address_array = [self.work_address_street, self.work_address_street2, self.work_address_city, self.work_address_state, self.work_address_country, self.work_address_postcode]
    @work_address_array.reject(&:blank?).join(", ")
  end

  def location
    @location_array = [self.address_city, self.address_state, self.address_country]
    @location_array.reject(&:blank?).join(", ")
  end

  friendly_id :name, use: :slugged
  geocoded_by :address
  after_validation :geocode

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @contacts = ApplicationPolicy::Scope.new(current_user, Contact).resolve.alphabetical
  end

  def show
    @notes = @contact.notes.reverse
    @tasks = @contact.tasks.reverse
    @hash = Gmaps4rails.build_markers(@contact) do |contact, marker|
      marker.lat contact.latitude
      marker.lng contact.longitude
    end

  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_variable
    @contact_detail = Contact.find(params[:contact_id])
      respond_to do |format|
      format.html
      format.js
    end
  end

  private
    def set_contact
      @contact = Contact.friendly.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:firstname, :surname, :birthday, :job_title, :website, :primary_phone, :email, :bio, :address_street, :address_street2, :address_city, :address_state, :address_postcode, :address_country, :latitude, :longitude, :referred_by, :twitter, :linkedin, :company_id, :image)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper

end

app/views/contacts/_contact_details.html.haml
.contact-details-image
  - if @contact_detail.image?
    = image_tag(@contact_detail.image.url(:standard))
  - else
    .initials.standard
      = @contact_detail.initials
.contact-block
  .contact-name
    = @contact_detail.name
  .contact-job
    = @contact_detail.job_title
= button_to 'View Profile', contact_path(@contact_detail), :method => 'get', :class => 'float-left'
.contact-info
  %h2.sub-title Contact Info
  .muted-text
    = @contact_detail.email
  .muted-text
    = @contact_detail.primary_phone
  %br
  .muted-text
    = @contact_detail.address_line1
  .muted-text
    = @contact_detail.address_line2
  .muted-text
    = @contact_detail.address_line3

  %h2.sub-title Personal Info

  .muted-text
    Birthday:
    = @contact_detail.full_age

app/views/contacts/_form.html.haml
= form_for contact, html: { multipart: true } do |f|
  - if contact.errors.any?
    #error_explanation
      %h2
        = pluralize(contact.errors.count, "error")
        prohibited this contact from being saved:
      %ul
        - contact.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :birthday
    = f.date_select :birthday, start_year: 1945, :class => 'four'
  .field
    = f.label :job_title
    = f.text_field :job_title
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :primary_phone
    = f.text_field :primary_phone
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :bio
    = f.text_area :bio
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :address_street
    = f.text_field :address_street
  .field
    = f.label :address_street2
    = f.text_field :address_street2
  .field
    = f.label :address_city
    = f.text_field :address_city
  .field
    = f.label :address_state
    = f.text_field :address_state
  .field
    = f.label :address_postcode
    = f.text_field :address_postcode
  .field
    = f.label :address_country
    = f.text_field :address_country
  .field
    = f.label :referred_by
    = f.text_field :referred_by
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :linkedin
    = f.text_field :linkedin
    = f.text_field :company_id, :value => current_user.company_id
  .actions
    = f.submit

app/views/contacts/edit.html.haml
= content_for(:title) do
  = "Editing #{@contact.name}'s record"
= content_for(:description) do
  = "Editing #{@contact.name}'s record"

%h1 Editing Contact
= render 'form', contact: @contact
= link_to 'Show', @contact
|
\#{link_to 'Back', contacts_path}

app/views/contacts/index.html.haml
= content_for(:title) do
  Contacts
= content_for(:description) do
  List of Contacts

%h1.floated-title
  Contacts
= button_to 'New Contact', new_contact_path, :method => 'get', :class => 'floated-button'
.filters
  .alphabetical
    = link_to do
      A - Z
      = fa_icon 'exchange'

  .name-order
    Surname, First Name
    = fa_icon 'exchange'

.contact-list.five
  - if @contacts.count == 0
    "No contacts here"
  - else
    - @contacts.each do |contact|
      = link_to contact_update_variable_path(:contact_id => contact.id), :remote => true, :method => 'get' do
        %div.contact-list-link
          .contact
            .contact-image
              - if contact.image?
                = image_tag(contact.image.url(:thumb))
              - else
                .initials.small
                  = contact.initials
            .contact-name
              = contact.name
            .contact-job
              = contact.job_title

.contact-details.seven
  #profile

app/views/contacts/new.html.haml
= content_for(:title) do
  Add New Contact
= content_for(:description) do
  Add New Contact


%h1 New Contact
= render 'form', contact: @contact
= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
= content_for(:title) do
  = @contact.name
= content_for(:description) do
  = @contact.name

.row
  .breadcrumbs
    = link_to 'Contacts', contacts_path
    \> #{@contact.name}

.row
  .show-contact.twelve
    .top-section.twelve
      .left-side.four
        .contact-show-image
          - if @contact.image?
            = image_tag(@contact.image.url(:standard))
          - else
            .initials.large
              = @contact.initials
        .contact-show-block
          .contact-name
            = @contact.name
          .contact-show-job
            = @contact.job_title
      .right-side.four
        = button_to 'Edit Profile', edit_contact_path(@contact), :method => 'get'

      .contact-show-info.twelve
        .contact-info.four
          %h2.sub-title
            Contact Info
          .muted-text
            = @contact.email
          .muted-text
            = @contact.primary_phone
          %br
          .muted-text
            = @contact.address_line1
          .muted-text
            = @contact.address_line2
          .muted-text
            = @contact.address_line3
        .personal-info.four
          %h2.sub-title
            Personal Info
          .muted-text
            = @contact.full_age
          %br
          .muted-text
            = @contact.bio
        - if (@contact.twitter.present?) || (@contact.linkedin.present?)
          .social-info.four
            %h2.sub-title
              Social Info
            - if @contact.twitter.present?
              .muted-text
                Twitter:
                = link_to "#{@contact.twitter}", "http://twitter.com/#{@contact.twitter}", :target => "_blank"
            - if @contact.linkedin.present?
              .muted-text
                LinkedIn:
                = link_to "#{@contact.linkedin}", "https://www.linkedin.com/in/#{@contact.linkedin}", :target => "_blank"

app/views/contacts/update_variable.js.erb
//$('#profile').replaceWith("#{escape_javascript(render partial: 'contacts/contact_details', locals: { contact: @contact_detail })}");

$('#profile').html('<%=j render partial: "/contacts/contact_details", locals: { @contact => @contact_detail } %> ');