config/routes.rb
Rails.application.routes.draw do

  resources :contacts do
    resources :notes
    resources :tasks
    get :update_variable
  end

  resources :companies

  devise_for :users
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "search/index"

  get '/all-tasks/' => 'tasks#allTasks', :as => :all_tasks
  get '/all-notes/' => 'notes#allNotes', :as => :all_notes
  get 'users/:id/preferences' => 'users#preferences', :as => :preferences

end

app/views/layouts/partials/_footer.html.haml
%footer
  .footer-content
    %p
      Copyright &copy;
      = Time.now.year
      %br
      Imagined &amp; crafted by
      = link_to 'Gareth D. Jones', 'http://garethdjones.com'

app/views/layouts/partials/_header.html.haml
%header.twelve

  = form_tag search_index_path, method: :get, :class => 'header-form eight' do
    = text_field_tag :query, params[:query], :placeholder => 'Type to Search...', :class => 'search-field'
  .settings-menu.four
    = link_to "Preferences", preferences_path(current_user), :class => 'settings-menu-link'
    = link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => 'settings-menu-link', :data => {:confirm => "Are you sure you wish to sign out?"}

app/views/layouts/partials/_notifications.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/partials/_sidebar.html.haml
%sidebar.three
  .sidebar-content
    .company
      .logo.four
        - if current_user.company.present?
          - if current_user.company.logo?
            = image_tag(current_user.company.logo.url(:thumb))
          - else
            = image_tag 'Logo.png', :title => "#{current_user.company.name}"
        - else
          = image_tag 'Logo.png', :title => "Logo"
      .details.eight
        - if signed_in?
          - if current_user.company.present?
            .company-name
              = current_user.company.name
          - if current_user.name.present?
            .user-name
              = current_user.name
          - else
            = current_user.email
          -# - if current_user.role == "admin"
          -#   \Admin
    .navigation
      %h2.area-title
        Areas
      %ul.page-navigation
        %li.navigation-item
          = link_to contacts_path do
            Contacts #{ApplicationPolicy::Scope.new(current_user, Contact).resolve.count}
        %li.navigation-item
          = link_to all_tasks_path do
            Tasks
        %li.navigation-item
          = link_to all_notes_path do
            Notes